apiVersion: v1
entries:
  web-app:
  - apiVersion: v2
    appVersion: 0.0.5
    created: "2023-01-25T08:10:49.581479867Z"
    description: A demo Helm chart for Kubernetes
    digest: 5e0982fb790cfd9f63957fe2f5433bd723dd6dc8dfe1f502d719722f22477ad8
    name: web-app
    type: application
    urls:
    - web-app-0.0.5.tgz
    version: 0.0.5
  - apiVersion: v2
    appVersion: 0.0.3
    created: "2023-01-25T08:10:49.581175078Z"
    description: A demo Helm chart for Kubernetes
    digest: 3cb9069b451cb9032f18e6de93fe6b6fc0a566c971d78e49add0331bb6501120
    name: web-app
    type: application
    urls:
    - web-app-0.0.3.tgz
    version: 0.0.3
  - apiVersion: v2
    appVersion: 0.0.2
    created: "2023-01-25T08:10:49.580832267Z"
    description: A demo Helm chart for Kubernetes
    digest: fab858ce2fc2f145aeaf84c3cff70f970586ad7534f62a3402f90cfc8e10fe6b
    name: web-app
    type: application
    urls:
    - web-app-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2023-01-25T08:10:49.580425502Z"
    description: A demo Helm chart for Kubernetes
    digest: 7cf04eb42a249f6bf6553f686601d526934eb8198256e2d5ab577a7946cf5546
    name: web-app
    type: application
    urls:
    - web-app-0.0.1.tgz
    version: 0.0.1
generated: "2023-01-25T08:10:49.579713247Z"
